### ISSUE TITLE
2017 volt recieving "Radar Fault" or "Cruise Error" while on OPGM 

### ISSUE THREAD

**Issue by brugsy** [opgm/openpilot#100]
While running stock OP, the system works as expected. When running on OPGM, it fails to enable OP listing either "cruise" or "radar" issue, and has trouble reading commands at times. This does not allow the system to work at all.

2017 Volt Premier with ACC and LKAS

**Comment by nworb-cire** [comment]
Can you confirm whether this is still an issue with the latest `build` branch?

**Comment by brugsy** [comment]
I have not seen this issue for a long time. Thanks.
