### ISSUE TITLE
Investigate means of resetting EPS without restarting car (Serial data comm enable pin)

### ISSUE THREAD

**Issue by JasonJShuler** [opgm/openpilot#13]
Note: I have confirmed that power-cycling the EPS effectively resets the fault, however using the power plug attached to the firewall kills power for most of the dash.

From what I can tell, the serial data communication enable pin is _THE_ method used by the car to control the EPS - the power is always connected.

A fuse interruptor is not going to be an option - the "fuse" is built-in to the positive battery terminal assembly and cannot be removed: even if it could, it is very high current - the car itself doesn't have a relay in the path...

**Comment by Verylukyguy** [comment]
This would be great.  A hard reset should never be required.
