### ISSUE TITLE
Bolt EUV LKAS fault appears occasionally

### ISSUE THREAD

**Issue by MadBrad** [opgm/openpilot#66]
I've gotten LKAS faults occasionally, but not too often. It usually happens if I quickly turn the car off and then back on again, but it has also happened while driving. The only way to fix it is to turn the car off completely, open and close the door, wait 3 minutes, and then start the car up again.

**Comment by Trilobyte17** [comment]
Same issue, EUV 2022 Premier with C3. Has happened a few times with OPGM engaged (dev-c3) when changing max speed and changing lanes in close timing to each other. Other times it has happened just driving the car around, without OPGM engaged.

**Comment by Cottamre** [comment]
I get it frequently in 2019 Bolt EV with AOL enabled.  Faults almost every time I brake and OPGM is enabled.

**Comment by nworb-cire** [comment]
This issue should largely have been resolved upstream, see e.g. https://github.com/commaai/openpilot/pull/26039. Please reopen this issue if you still experience the problem.

@Cottamre you are experiencing a different issue related to AOL, which should be resolved in the next release. Feel free to install the dev branch in the meanwhile and give feedback on discord.
